const contacts=[
{id:"SS-017",name:"Auntie Static",district:"Heywood",service:"Information",note:"Rumor verification, family tracing, old CitiNet records.",terms:"Calls back between 02:00 and 04:00. Never ask where she got a municipal seal.",number:"HEY-77-STATIC",risk:"green"},
{id:"SS-031",name:"Latchkey",district:"Santo Domingo",service:"Goods",note:"Industrial tools, replacement parts, sealed crates.",terms:"Cash or useful schematics. No refunds after a crate leaves the loading floor.",number:"SD-44-LATCH",risk:"amber"},
{id:"SS-044",name:"Saint Monday",district:"Pacifica",service:"People",note:"Introductions, temporary muscle, venue access.",terms:"Every introduction creates a favor. He decides when the favor matures.",number:"PAC-0-MONDAY",risk:"red"},
{id:"SS-052",name:"Coyote Nine",district:"Nomad routes",service:"Transport",note:"Cargo passage east, passenger passage if quiet.",terms:"Routes change nightly. Payment doubles if anyone uses a legal name.",number:"ALD-COY-009",risk:"green"},
{id:"SS-068",name:"Mister Suds",district:"Heywood",service:"Cleanup",note:"Vehicle interiors, apartments, small storefronts.",terms:"Quotes exclude ammunition, chemical neutralization, and witnesses who return.",number:"GLN-SUDS-6",risk:"amber"},
{id:"SS-081",name:"Pocket Change",district:"Santo Domingo",service:"Goods",note:"Credchip exchange and debt consolidation.",terms:"Directory mirror cannot confirm that this is one person or a person at all.",number:"SD-1-CHNGE",risk:"red"}
,{id:"SS-096",name:"Velvet Hammer",district:"Heywood",service:"People",note:"Quiet door staff, visible deterrence, difficult conversations.",terms:"Minimum four-hour booking. Clients pay for damaged suits before damaged walls.",number:"GLN-VELVET-4",risk:"green"}
,{id:"SS-103",name:"Kilometer",district:"Nomad routes",service:"Information",note:"Road conditions, convoy sightings, border timing.",terms:"One answer costs one answer. False information is remembered longer than debt.",number:"RTE-KM-103",risk:"amber"}
,{id:"SS-117",name:"Motherboard",district:"Santo Domingo",service:"Cleanup",note:"Data-room stripouts, abandoned architectures, hardware disappearance.",terms:"Will not touch active Black ICE. Will decide for herself what counts as active.",number:"SD-M0THER",risk:"red"}
,{id:"SS-126",name:"Palisade",district:"Pacifica",service:"Transport",note:"Armored pickup, short corridor extraction, sealed passenger compartment.",terms:"Destination must be disclosed before arrival. Cargo questions cost extra.",number:"PAC-WALL-26",risk:"amber"}
];
const ledger=document.querySelector("#ledger"),search=document.querySelector("#search"),district=document.querySelector("#district"),service=document.querySelector("#service"),dialog=document.querySelector("#contact");
function render(){const q=search.value.toLowerCase();const shown=contacts.filter(c=>(district.value==="all"||c.district===district.value)&&(service.value==="all"||c.service===service.value)&&(`${c.name} ${c.note} ${c.district} ${c.service}`).toLowerCase().includes(q));document.querySelector("#count").textContent=shown.length;ledger.innerHTML="";shown.forEach(c=>{const article=document.createElement("article");article.className="entry";article.innerHTML=`<i class="risk ${c.risk}" aria-label="${c.risk} risk"></i><div><h2>${c.name}</h2><p>${c.note}</p></div><span>${c.district}</span><small>${c.service.toUpperCase()}<br>${c.id}</small><button>REVEAL CONTACT</button>`;article.querySelector("button").addEventListener("click",()=>openContact(c));ledger.appendChild(article)});if(!shown.length)ledger.innerHTML='<p class="empty">NO MATCH. That may be good news.</p>'}
function openContact(c){dialog.querySelector("h2").textContent=c.name;dialog.querySelector(".number").textContent=c.number;dialog.querySelector(".terms").textContent=c.terms;dialog.querySelector(".result").textContent="";dialog.showModal()}
[search,district,service].forEach(el=>el.addEventListener(el===search?"input":"change",render));dialog.querySelector(".close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});dialog.querySelector("form").addEventListener("submit",e=>{e.preventDefault();dialog.querySelector(".result").textContent="Relay accepted. Delivery receipt unavailable. Do not send it twice.";e.currentTarget.reset()});render();
document.querySelector("#random").addEventListener("click",()=>{const pick=contacts[Math.floor(Math.random()*contacts.length)];search.value=pick.name;district.value="all";service.value="all";render();document.querySelector("#ledger").scrollIntoView({behavior:"smooth"})});
